### ISSUE TITLE
Config:target for interwiki and external links doesn't work unless the visitor is logging in as an admin

### ISSUE THREAD

**Issue by hokkaidoperson** [tatewake/dokuwiki-plugin-googleanalytics#10]
While using this plugin, [the target configurations](https://www.dokuwiki.org/config:target) for interwiki and external links don't work, and the links open in the same tab.

The configuration for internal links works properly.  I'm not sure whether the conf for windows share links has the same problem.

Confs:
target»interwiki: _blank
target»extern: _blank

[Googleanalytics]
dont_count_admin: 1
dont_count_users: 0
anonymize: 1
track_users: 0
track_links: 1
domainName: (null)

Reproduction:
1. Set configurations according to the "Confs" above
2. Go to a page with interwiki link(s) and external link(s), or make a page with the links
3. If you are not logging in, or logging in as a general user (not admin), interwiki links and external links don't open in the new tab.
4. Log in as an admin, and the links open in the new tab.

**Comment by tatewake** [comment]
This is a really strange side-effect since this plugin shoudn't have anything to do with how links work… however I'll look into it when I get a chance.

**Comment by phy25** [comment]
This is happening because of how `track_links` is implemented:

https://github.com/tatewake/dokuwiki-plugin-googleanalytics/blob/f02bbb2972d3bc19bb03550676e600946eeca982/script.js#L37-L52

It will open the link regardless of "target" attribute. Looks difficult to respect the attribute gracefully by JavaScript.

**Comment by tatewake** [comment]
Should be fixed as of today's release.
