### ISSUE TITLE
No Google Analytics data

### ISSUE THREAD

**Issue by cpedraza-ca** [tatewake/dokuwiki-plugin-googleanalytics#11]
I'm seeing zero data on Google Analytics from my site. I used to see plenty of data. The plugin configuration has the correct Google UA ID number. My dashboard displays the following notification:

  _"Property [site name] is not receiving hits. Either your site is not receiving any sessions or it is not tagged correctly.
  "Google Tag Assistant Recordings can help you ensure that your site is tagged correctly."_

**Comment by tatewake** [comment]
Should be fixed as of today's release.
