### ISSUE TITLE
Links do not work when enabled

### ISSUE THREAD

**Issue by gerardorourke** [tatewake/dokuwiki-plugin-googleanalytics#12]
Left Clicking and selecting a link does not work when the Google Analytics Plugin is enabled.
Example dokuwiki text:

http://www.google.ie

Regards,
Gerard.

**Comment by phy25** [comment]
Hello, I tried on my local wiki site and it works. Could you please post your config (a demo site would be better), and check other plugins as well?

**Comment by gerardorourke** [comment]
I disabled every single plugin except for Google Analytics and it didn't fix it. 
I changed the template from bootstrap 3 to standard dokuwiki template and it didn't fix the issue.

![GA-dokuconfig](https://user-images.githubusercontent.com/45767773/55795360-8188f280-5abf-11e9-86e9-69e82761a030.png)

**Comment by phy25** [comment]
It works well on my end with DokuWiki Release 2018-04-22a "Greebo", plugin version "2017-02-07".

You may want to open Web Developer on your browser to see if there's any error when clicking. Also a demo site would be better.

**Comment by gerardorourke** [comment]
Thanks Phy25. 

I looked at the browser logs. In firefox this was not working because Strict content blocking was enabled (Options -> Privacy & Security -> Content Blocking -> Strict).
It is warned that this can break some sites - but this is the first time it has impacted me, by breaking a website functionality.

In Chrome it was not working as I had Ghostery chrome plugin. I hadn't tried IE! (which worked OK!).
If Ghostery is disabled / removed or if firefox is set to standard (Only blocks known trackers in Private Windows.)  The Links **do** work.

However there is still an issue on both Chrome & Firefox.

When Google Analytics Dokuwiki Plugin is enabled, the links work, but if you try to use (on windows) CTRL + click link, it should open the link in a **new tab.** 
But it opens in the same tab. Not as big an issue - but still an issue.

Also if you do set Strict content blocking on Firefox (or use Ghostery) instead of breaking the website functionality, ideally it should still work (but google analytics would just get blocked).

At least we know how to reproduce the issue now.

Gerry

**Comment by phy25** [comment]
I see. Looks like it's related to `track_links`, and it's not that robust here:

https://github.com/tatewake/dokuwiki-plugin-googleanalytics/blob/f02bbb2972d3bc19bb03550676e600946eeca982/script.js#L40-L49

A quick workaround is to disable `track_links` (and it will never track links).

**Comment by gerardorourke** [comment]
Phy25,

Thanks. I can confirm disabling 'Track outgoing links' restores functionality even with Firefox set to strict content blocking. 

Gerry

**Comment by tatewake** [comment]
Hi guys, I've been following this, sorry I haven't spoken up so far… @phy25 what's your thought… is this something that we could potentially address within the plugin (I'm guessing a fix in the JavaScript within that jQuery click handler), or is this something that's a bigger issue within DokuWiki as a whole?

**Comment by phy25** [comment]
@tatewake I can make a PR for this. Looks like Firefox's strict private mode is blocking ga.js from loading, and the JavaScript code I mentioned above doesn't handle that so good (There's no `ga()` and thus `hitCallback` never gets executed).

**Comment by tatewake** [comment]
Sounds good @phy25 ; take your time of course. We're probably due for a refresh release anyway. Thanks for your help as always.
