### ISSUE TITLE
The attribute value target is not respected when trackOutboundLinks is on

### ISSUE THREAD

**Issue by gerardnico** [tatewake/dokuwiki-plugin-googleanalytics#15]
Hallo,

There is an [e.preventDefault](https://github.com/tatewake/dokuwiki-plugin-googleanalytics/blob/master/script.js#L44) in the OutboundLinks Jquery function that makes the link open in the same window in place of a new tab if the `target` attribute is set to `_blank`

I don't know why it's their. When I delete it, it's working as expected.

PR to come.

Cheers
Nico

**Comment by gerardnico** [comment]
I never known where I need to write so I do it also on the ticket. The callback is not needed. I think that the documentation shows how to take control over the event but as far as I know, there is no need for the plugin.

Doc: https://support.google.com/analytics/answer/1136920?hl=en

**Comment by phy25** [comment]
Why is the callback in the documentation not needed? How do you ensure Google Analytics tracking is recorded?

**Comment by phy25** [comment]
My bad. Looks like when this code is initially introduced, `transport: beacon` is already used, and thus there is no need to wait for the request to complete.

**Comment by tatewake** [comment]
I believe this is the issue you solved in #16 , so I'm going to close this.
