### ISSUE TITLE
After updating, it still says it needs updating

### ISSUE THREAD

**Issue by tofighi** [tatewake/dokuwiki-plugin-googleanalytics#8]
The status of plugin will not change after updating to the latest version.

**Comment by MikkCZ** [comment]
I am not sure, how DokuWiki plugin mechanism works, but I have noticed the administration shows version available to be 2017-02-08, while plugin.info.txt file contains date 2017-02-07. So I have just updated the date in `lib/plugins/googleanalytics/plugin.info.txt` and the update prompt disappeared.

**Comment by tatewake** [comment]
Should be fixed as of today's release.
