### ISSUE TITLE
Modification of template required?

### ISSUE THREAD

**Issue by GJRobert** [tatewake/dokuwiki-plugin-googleanalytics#9]
Hi there,

I have tried to follow all steps on the [DokuWiki page](https://www.dokuwiki.org/plugin:googleanalytics?s[]=google&s[]=analytics), but Google Analytics still does not receive any data from my site: http://ghsrobert.tk/ .

I have read the information from these two pages:
- [Google Analytics for DokuWiki - TJ Grant](http://tjgrant.com/wiki/projects:google_analytics_for_dokuwiki)
- [Google Analytics Plugin - DokuWiki User Forum](https://forum.dokuwiki.org/thread/1591)

So, do I have to further modify any of my templates to make this plugin work?

**Comment by tatewake** [comment]
Hi. So I looked at your site and I don't see any Google Analytics code there.

Follow the instructions here to properly set up Google Analytics:

 * https://www.dokuwiki.org/plugin:googleanalytics

The "user forum" link you listed is 10 years old, and Google Analytics has changed since then.

**Comment by GJRobert** [comment]
Hi tatewake,

Yes your instructions on [DokuWiki] plugin:googleanalytics was my first reference. I believed that I have followed the steps as possible as I can, but the result is indeed like what you have seen, no code appearing.

Now I'm creating new GAnalytics properties as told again. Could you share how you check if Google codes are successfully inserted on my site so that I can test if I have done the right thing or not?

**Comment by GJRobert** [comment]
This is what I have done again this time:

1. Set up a new property (domain: ghsrobert.tk): DONE; tracking code got
1. Custom dimentions: DONE
1. User ID tracking: SUSPENDED
1. View: I chose the default one "All site data" (or some similar English title), and enabled Site Search Tracking, DONE
1. Install the plugin on DokuWiki: ALREADY (but it's installed on my "farmer" site, and "ghsrobert.tk" is a farm animal)
1. Fill the tracking code in the system config: DONE

And from the information provided by Google Tag Assistant, there are still no Google tags/code found on my site.

My DokuWiki version: 2017
Template used here: writr

Would appreciate if any clues, thanks!

**Comment by phy25** [comment]
There are errors in your theme's JavaScript (see console messages by F12), which causes the part of GA insertion in the js.php unable to run.

**Comment by GJRobert** [comment]
Hi phy25,

Thanks for your hint. Do I have to solve all the errors in the js.php so to allow GA insertion to work?

(It seems that the errors are related to 2 or 3 plugins of mine)

**Comment by phy25** [comment]
Yes, because they are in the same compressed JS file, and the GA part is in the end of the file, which will be blocked by the previous errors.

**Comment by GJRobert** [comment]
Hi,

There has been progress after I disabled 3 plugins of mine. Now googleanalytics seems to be ready to run. Still one error from http://ghsrobert.tk :
```
js.php?t=writr&tseed=bdf7b17835357011097eb195b3892c5d:65377 GET https://www.google-analytics.com/analytics.js net::ERR_CONNECTION_REFUSED
(anonymous) @ js.php?t=writr&tseed=bdf7b17835357011097eb195b3892c5d:65377
(anonymous) @ js.php?t=writr&tseed=bdf7b17835357011097eb195b3892c5d:65378
```
Is there anything I can do to improve this?

**Comment by phy25** [comment]
@GJRobert Didn't see that error on your website. It might be temporary network error.

**Comment by GJRobert** [comment]
@phy25 Thank you so much for your check and information, now I can finally see traffic data on my Analytics dashboard. Hurray!

**Comment by tatewake** [comment]
Thanks @phy25 for the resolution to this. Closing ticket.
